# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/igor/NTS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/igor/NTS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igor/NTS/CMakeFiles /home/igor/NTS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igor/NTS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NTSlib

# Build rule for target.
NTSlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NTSlib
.PHONY : NTSlib

# fast build rule for target.
NTSlib/fast:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/build
.PHONY : NTSlib/fast

#=============================================================================
# Target rules for targets named NTS

# Build rule for target.
NTS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NTS
.PHONY : NTS

# fast build rule for target.
NTS/fast:
	$(MAKE) -f CMakeFiles/NTS.dir/build.make CMakeFiles/NTS.dir/build
.PHONY : NTS/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/NTS.dir/build.make CMakeFiles/NTS.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/NTS.dir/build.make CMakeFiles/NTS.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/NTS.dir/build.make CMakeFiles/NTS.dir/main.c.s
.PHONY : main.c.s

src/init_nts.o: src/init_nts.c.o

.PHONY : src/init_nts.o

# target to build an object file
src/init_nts.c.o:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/init_nts.c.o
.PHONY : src/init_nts.c.o

src/init_nts.i: src/init_nts.c.i

.PHONY : src/init_nts.i

# target to preprocess a source file
src/init_nts.c.i:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/init_nts.c.i
.PHONY : src/init_nts.c.i

src/init_nts.s: src/init_nts.c.s

.PHONY : src/init_nts.s

# target to generate assembly for a file
src/init_nts.c.s:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/init_nts.c.s
.PHONY : src/init_nts.c.s

src/log_process.o: src/log_process.c.o

.PHONY : src/log_process.o

# target to build an object file
src/log_process.c.o:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/log_process.c.o
.PHONY : src/log_process.c.o

src/log_process.i: src/log_process.c.i

.PHONY : src/log_process.i

# target to preprocess a source file
src/log_process.c.i:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/log_process.c.i
.PHONY : src/log_process.c.i

src/log_process.s: src/log_process.c.s

.PHONY : src/log_process.s

# target to generate assembly for a file
src/log_process.c.s:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/log_process.c.s
.PHONY : src/log_process.c.s

src/logfile_proc.o: src/logfile_proc.c.o

.PHONY : src/logfile_proc.o

# target to build an object file
src/logfile_proc.c.o:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/logfile_proc.c.o
.PHONY : src/logfile_proc.c.o

src/logfile_proc.i: src/logfile_proc.c.i

.PHONY : src/logfile_proc.i

# target to preprocess a source file
src/logfile_proc.c.i:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/logfile_proc.c.i
.PHONY : src/logfile_proc.c.i

src/logfile_proc.s: src/logfile_proc.c.s

.PHONY : src/logfile_proc.s

# target to generate assembly for a file
src/logfile_proc.c.s:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/logfile_proc.c.s
.PHONY : src/logfile_proc.c.s

src/signal.o: src/signal.c.o

.PHONY : src/signal.o

# target to build an object file
src/signal.c.o:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/signal.c.o
.PHONY : src/signal.c.o

src/signal.i: src/signal.c.i

.PHONY : src/signal.i

# target to preprocess a source file
src/signal.c.i:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/signal.c.i
.PHONY : src/signal.c.i

src/signal.s: src/signal.c.s

.PHONY : src/signal.s

# target to generate assembly for a file
src/signal.c.s:
	$(MAKE) -f CMakeFiles/NTSlib.dir/build.make CMakeFiles/NTSlib.dir/src/signal.c.s
.PHONY : src/signal.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NTSlib"
	@echo "... NTS"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/init_nts.o"
	@echo "... src/init_nts.i"
	@echo "... src/init_nts.s"
	@echo "... src/log_process.o"
	@echo "... src/log_process.i"
	@echo "... src/log_process.s"
	@echo "... src/logfile_proc.o"
	@echo "... src/logfile_proc.i"
	@echo "... src/logfile_proc.s"
	@echo "... src/signal.o"
	@echo "... src/signal.i"
	@echo "... src/signal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

